### ISSUE TITLE
pkg_groups implementation in AOK

### ISSUE THREAD

**Issue by jaclu** [emkey1/AOK-Filesystem-Tools#8]
I thought it would make sense to open a thread here, so we can get some consensus of replacing the current bloat script

For ease of reference I reprise my questions here:

For now, and to not risk interferance with other stuff, I added it under
its current name pkg_group
I originally use this in jaclu/spd, so therefore in order to use the AOK
groups param -a has to be given currently to use yours.

So some questions:

A) Is it your preference to keep the bloat group definitions in
/usr/local/etc/AOK_VARS to support other tools? If so then they should stay,
if not it could be put inside pkg_group.

B) If you wanted to keep the groups in its current location, is it ok
to just change the bloat script to run pkg_group -a?
this way I can keep the main code of pkg_group identical in AOK / spd
potentially only changing the group definitions. This would make it much
easier for me to keep updates of pkg_group in sync.

C) If bloat is chaining pkg_group, is maintaining the current syntax for bloat
a must (the group names not matching actual group names) - can certainly be
done, but if it was only used for human consumption, it doesn't serve any
purpose, since that interface, well was sub-optimal :) If it is used from
scripts, then it might make sense to ensure it can be used with the same
notation as before.

D) currently I am removing BLOAT and _APKS from the group names,
and lower casing them, to make it more visually palatable :)
If other tools depend on the current group names when calling bloat
this is super easy to undo, just let me know.

**Comment by emkey1** [comment]
Cool!

In regards to question A, I created the AOK_VARS file to avoid having to modify scripts as often,  Say for instance when I wanted to add an apk to one of the bloat levels, or remove something.  It has stuff that impacts both the scripts to build an AOK root .tgz, as well as things that impact how bloat and vnc_enable operate.  To be honest, it could certainly be done better.  It's also incomplete in the sense that the motd file for instance doesn't get modified based on what is contained in AOK_VARS for versioning when the rootfs is built.  I'd be more than happy to see something that sucks less.

On B, certainly!

On C, no.  I don't know that very many people use it at this point.  The TestFlight has <100 active testers right now.  I'd like to see that number increase, so changing it sooner rather than later makes sense to me.

D, no dependencies that I recall.  Capitalising variables like that is a 'me' convention.  I'm not wedded to it.

**Comment by jaclu** [comment]
So if I get you right, the groups should continue to be defined in the AOK file as is now the case, no need to change the current naming conventions there, Im just translating them for easier usage in pkg_groups
and I will change bloat to essentially become pkg_groups -a "$@"
once you approve
